### ISSUE TITLE
Fix to docker-compose sample to make it independent from docker-machine

### ISSUE THREAD

**Issue by gschmutz** [lyft/amundsensearchlibrary#18]
For running the containers without docker-machine but just docker-compose I had to add the capability to configure the Elasticsearch endpoint by an environment variable (similar to the behaviour of the frontend service where search and metadata service endpoint can be configured). 
The fix is available in this PR: #16 . Additionally I also had to teak the docker-compose.yml for amundsensearch and amundsenmetadata service as shown below. Should I create a PR for the docker-amundsen.yml as well or do you want it to keep the way it is (so it works with docker-machine)?

```
  amundsensearch:
      image: gschmutz/amundsen-search:latest
      container_name: amundsensearch
      ports:
        - 5001:5000
      depends_on:
        - elasticsearch
      environment:
        - ELASTICSEARCH_BASE=http://elasticsearch:9200
      networks:
        - amundsennet
  amundsenmetadata:
      image: amundsendev/amundsen-metadata:latest
      container_name: amundsenmetadata
      depends_on:
        - neo4j
      environment:
        - CREDENTIALS_PROXY_USER=neo4j
        - CREDENTIALS_PROXY_PASSWORD=test
        - PROXY_HOST=bolt://neo4j
        - PROXY_PORT=7687
        - PROXY_CLIENT=NEO4J
      ports:
        - 5002:5000
      networks:
        - amundsennet
```
